apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-container
          image: tarungiri1991/todo-api:2.1
          ports:
            - containerPort: 80
          env:
            - name: Database__ServerName
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: DATABASE_SERVER
            - name: Database__UserId
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: DATABASE_USER_ID
            - name: Database__Password
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: DATABASE_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
spec:
  rules:
    - host: mytodoapp.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-service
                port:
                  number: 80
